# Generated by Django 3.0.4 on 2020-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('profile', models.CharField(choices=[('научный', 'научный'), ('историчекский', 'историчекский')], max_length=100, verbose_name='Профиль')),
                ('wth', models.CharField(choices=[('друг', 'друзья'), ('семь', 'семья'), ('реб', 'дети')], max_length=100, verbose_name='С кем-то')),
                ('price', models.CharField(choices=[('дёшево', 'от 100-299'), ('дорого', 'от 300')], max_length=100, verbose_name='Цена')),
                ('time', models.CharField(choices=[('утро', '06:00-11:59'), ('день', '12:00-17:99'), ('вечер', '18:00-23:99')], max_length=100, verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
